import {
  AcademicClass,
  AcademicSubject,
  AcademicChapter,
  EducationalContent,
  PackageItem,
  Student,
  PaymentTransaction,
  DashboardFeatureConfig,
  GlobalWebsiteSettings,
  AnnouncementItem,
  NotificationItem,
  AdminUser,
  AdminActivityLog,
} from '../types/admin';

export const INITIAL_ADMIN_USERS: AdminUser[] = [
  {
    id: 'adm_1',
    name: 'Super Administrator',
    email: 'admin@beyondclassroom.com',
    role: 'super_admin',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
    isEnabled: true,
    twoFactorEnabled: true,
    lastLogin: '2026-08-16 21:30',
    createdAt: '2025-01-10',
    permissions: ['all'],
  },
  {
    id: 'adm_2',
    name: 'Dr. Sarah Jenkins',
    email: 'content@beyondclassroom.com',
    role: 'content_admin',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=120&auto=format&fit=crop&q=80',
    isEnabled: true,
    twoFactorEnabled: false,
    lastLogin: '2026-08-16 18:45',
    createdAt: '2025-02-15',
    permissions: ['content_manage', 'curriculum_edit', 'papers_publish'],
  },
  {
    id: 'adm_3',
    name: 'Vikram Malhotra',
    email: 'support@beyondclassroom.com',
    role: 'support_admin',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80',
    isEnabled: true,
    twoFactorEnabled: false,
    lastLogin: '2026-08-16 19:15',
    createdAt: '2025-03-01',
    permissions: ['student_support', 'payments_view', 'access_override_request'],
  },
];

export const INITIAL_CLASSES: AcademicClass[] = [
  { id: 'class_1', gradeNumber: 1, name: 'Class 1 Mathematics', shortName: 'Class 1', isEnabled: true, sortOrder: 1, description: 'Foundational Numbers, Counting, Shapes, Basic Addition & Subtraction' },
  { id: 'class_2', gradeNumber: 2, name: 'Class 2 Mathematics', shortName: 'Class 2', isEnabled: true, sortOrder: 2, description: '2-digit arithmetic, Place value, Basic Measurement, Simple Word Problems' },
  { id: 'class_3', gradeNumber: 3, name: 'Class 3 Mathematics', shortName: 'Class 3', isEnabled: true, sortOrder: 3, description: 'Multiplication Tables, Division Intro, Fractions Basics, Geometry' },
  { id: 'class_4', gradeNumber: 4, name: 'Class 4 Mathematics', shortName: 'Class 4', isEnabled: true, sortOrder: 4, description: 'Factors & Multiples, Decimals, Perimeter & Area, Time & Money' },
  { id: 'class_5', gradeNumber: 5, name: 'Class 5 Mathematics', shortName: 'Class 5', isEnabled: true, sortOrder: 5, description: 'Large Numbers, Operations, Fractions, Decimals, Geometry, Data Handling' },
  { id: 'class_6', gradeNumber: 6, name: 'Class 6 Mathematics', shortName: 'Class 6', isEnabled: true, sortOrder: 6, description: 'Integers, Algebra Intro, Ratio & Proportion, Mensuration, Practical Geometry' },
  { id: 'class_7', gradeNumber: 7, name: 'Class 7 Mathematics', shortName: 'Class 7', isEnabled: true, sortOrder: 7, description: 'Lines & Angles, Triangles, Rational Numbers, Algebraic Expressions, Exponents' },
  { id: 'class_8', gradeNumber: 8, name: 'Class 8 Mathematics', shortName: 'Class 8', isEnabled: true, sortOrder: 8, description: 'Linear Equations, Quadrilaterals, Squares & Roots, Factorisation, Mensuration' },
];

export const INITIAL_SUBJECTS: AcademicSubject[] = [
  { id: 'subj_1_math', classId: 'class_1', name: 'Core Mathematics', code: 'MTH_01', isEnabled: true, sortOrder: 1, description: 'Numbers & Shapes' },
  { id: 'subj_1_mental', classId: 'class_1', name: 'Speed & Mental Math', code: 'MNT_01', isEnabled: true, sortOrder: 2, description: 'Visual calculation tricks' },
  { id: 'subj_2_math', classId: 'class_2', name: 'Core Mathematics', code: 'MTH_02', isEnabled: true, sortOrder: 1 },
  { id: 'subj_2_mental', classId: 'class_2', name: 'Mental Math & Reasoning', code: 'MNT_02', isEnabled: true, sortOrder: 2 },
  { id: 'subj_3_math', classId: 'class_3', name: 'Core Mathematics', code: 'MTH_03', isEnabled: true, sortOrder: 1 },
  { id: 'subj_4_math', classId: 'class_4', name: 'Core Mathematics', code: 'MTH_04', isEnabled: true, sortOrder: 1 },
  { id: 'subj_5_math', classId: 'class_5', name: 'Core Mathematics', code: 'MTH_05', isEnabled: true, sortOrder: 1, description: 'NCERT / CBSE / ICSE Standard' },
  { id: 'subj_5_olympiad', classId: 'class_5', name: 'Math Olympiad & IMO Prep', code: 'OLY_05', isEnabled: true, sortOrder: 2, description: 'Competitive problems & logic' },
  { id: 'subj_6_math', classId: 'class_6', name: 'Core Mathematics', code: 'MTH_06', isEnabled: true, sortOrder: 1 },
  { id: 'subj_6_olympiad', classId: 'class_6', name: 'Olympiad & Reasoning', code: 'OLY_06', isEnabled: true, sortOrder: 2 },
  { id: 'subj_7_math', classId: 'class_7', name: 'Core Mathematics', code: 'MTH_07', isEnabled: true, sortOrder: 1 },
  { id: 'subj_8_math', classId: 'class_8', name: 'Core Mathematics', code: 'MTH_08', isEnabled: true, sortOrder: 1 },
  { id: 'subj_8_applied', classId: 'class_8', name: 'Applied Math & Geometry', code: 'APP_08', isEnabled: true, sortOrder: 2 },
];

export const INITIAL_CHAPTERS: AcademicChapter[] = [
  // Class 5 Chapters
  { id: 'ch_5_1', classId: 'class_5', subjectId: 'subj_5_math', chapterNumber: 1, title: 'The Fish Tale (Large Numbers & Place Value)', description: 'Place values up to Crores, Indian and International system, Real-life word problems.', isEnabled: true, sortOrder: 1 },
  { id: 'ch_5_2', classId: 'class_5', subjectId: 'subj_5_math', chapterNumber: 2, title: 'Shapes and Angles (Geometry)', description: 'Acute, Obtuse, Right angles, Degree clock, Protractor measurements.', isEnabled: true, sortOrder: 2 },
  { id: 'ch_5_3', classId: 'class_5', subjectId: 'subj_5_math', chapterNumber: 3, title: 'How Many Squares? (Area & Perimeter)', description: 'Grid area calculations, Irregular shapes, Formula for Rectangle and Square.', isEnabled: true, sortOrder: 3 },
  { id: 'ch_5_4', classId: 'class_5', subjectId: 'subj_5_math', chapterNumber: 4, title: 'Parts and Wholes (Fractions)', description: 'Proper, Improper, Mixed fractions, Equivalent fractions and addition.', isEnabled: true, sortOrder: 4 },
  { id: 'ch_5_5', classId: 'class_5', subjectId: 'subj_5_math', chapterNumber: 5, title: 'Tenths and Hundredths (Decimals)', description: 'Decimal place value, Conversion between Fractions and Decimals, Money arithmetic.', isEnabled: true, sortOrder: 5 },
  { id: 'ch_5_6', classId: 'class_5', subjectId: 'subj_5_math', chapterNumber: 6, title: 'Boxes and Sketches (3D & Spatial)', description: 'Nets of cube, 2D representations of 3D objects, isometric perspectives.', isEnabled: true, sortOrder: 6 },
  { id: 'ch_5_7', classId: 'class_5', subjectId: 'subj_5_olympiad', chapterNumber: 1, title: 'Logical Reasoning & Pattern Analysis', description: 'Number series, geometric puzzles, coding-decoding for Olympiads.', isEnabled: true, sortOrder: 1 },

  // Class 6 Chapters
  { id: 'ch_6_1', classId: 'class_6', subjectId: 'subj_6_math', chapterNumber: 1, title: 'Knowing Our Numbers', description: 'Comparing large numbers, Estimation, Roman numerals.', isEnabled: true, sortOrder: 1 },
  { id: 'ch_6_2', classId: 'class_6', subjectId: 'subj_6_math', chapterNumber: 2, title: 'Whole Numbers & Properties', description: 'Closure, Commutative, Associative and Distributive laws.', isEnabled: true, sortOrder: 2 },
  { id: 'ch_6_3', classId: 'class_6', subjectId: 'subj_6_math', chapterNumber: 3, title: 'Playing with Numbers (Factors & Multiples)', description: 'Prime factorization, HCF, LCM, Divisibility rules.', isEnabled: true, sortOrder: 3 },
  { id: 'ch_6_4', classId: 'class_6', subjectId: 'subj_6_math', chapterNumber: 4, title: 'Integers on the Number Line', description: 'Positive and negative numbers, Addition and subtraction of integers.', isEnabled: true, sortOrder: 4 },
  { id: 'ch_6_5', classId: 'class_6', subjectId: 'subj_6_math', chapterNumber: 5, title: 'Algebra: Introduction to Variables', description: 'Variables in expressions, Equations and standard solutions.', isEnabled: true, sortOrder: 5 },

  // Class 7 Chapters
  { id: 'ch_7_1', classId: 'class_7', subjectId: 'subj_7_math', chapterNumber: 1, title: 'Integers & Arithmetic Laws', description: 'Multiplication & division of negative numbers, BODMAS.', isEnabled: true, sortOrder: 1 },
  { id: 'ch_7_2', classId: 'class_7', subjectId: 'subj_7_math', chapterNumber: 2, title: 'Fractions and Decimals Mastery', description: 'Multiplication & division of fractional quantities.', isEnabled: true, sortOrder: 2 },
  { id: 'ch_7_3', classId: 'class_7', subjectId: 'subj_7_math', chapterNumber: 3, title: 'Simple Equations', description: 'Transposition method, word problem formulations.', isEnabled: true, sortOrder: 3 },

  // Class 8 Chapters
  { id: 'ch_8_1', classId: 'class_8', subjectId: 'subj_8_math', chapterNumber: 1, title: 'Rational Numbers & Number Line Properties', description: 'Density property, additive and multiplicative inverse.', isEnabled: true, sortOrder: 1 },
  { id: 'ch_8_2', classId: 'class_8', subjectId: 'subj_8_math', chapterNumber: 2, title: 'Linear Equations in One Variable', description: 'Equations with variables on both sides, age and speed problems.', isEnabled: true, sortOrder: 2 },
  { id: 'ch_8_3', classId: 'class_8', subjectId: 'subj_8_math', chapterNumber: 3, title: 'Understanding Quadrilaterals & Polygons', description: 'Angle sum property, Parallelograms, Rhombus, Trapezius theorems.', isEnabled: true, sortOrder: 3 },
  { id: 'ch_8_4', classId: 'class_8', subjectId: 'subj_8_math', chapterNumber: 4, title: 'Squares and Square Roots', description: 'Prime factorization method, Long division square roots.', isEnabled: true, sortOrder: 4 },
];

export const INITIAL_CONTENTS: EducationalContent[] = [
  {
    id: 'cnt_5_1_pp1',
    class_id: 'class_5',
    subject_id: 'subj_5_math',
    chapter_id: 'ch_5_1',
    content_type: 'practice_paper',
    title: 'Practice Paper 1: Large Numbers, Place Value & Indian System',
    description: '15 Curated questions testing standard Indian vs International numeration, expanded form, and word problems.',
    difficulty: 'medium',
    access_type: 'package_restricted',
    package_ids: ['pkg_pro', 'pkg_basic', 'pkg_school'],
    is_published: true,
    is_enabled: true,
    time_limit_minutes: 45,
    total_marks: 50,
    question_count: 15,
    pdf_url: '/downloads/class5_ch1_paper1.pdf',
    has_answer_key: true,
    has_step_by_step_solutions: true,
    has_hints: true,
    sort_order: 1,
  },
  {
    id: 'cnt_5_1_free',
    class_id: 'class_5',
    subject_id: 'subj_5_math',
    chapter_id: 'ch_5_1',
    content_type: 'practice_paper',
    title: 'Free Diagnostic Sample: Class 5 Place Value & Arithmetic',
    description: 'Free sample paper accessible to all public visitors and unregistered users to experience Beyond Classroom quality.',
    difficulty: 'easy',
    access_type: 'free',
    package_ids: ['pkg_free', 'pkg_pro', 'pkg_basic', 'pkg_school'],
    is_published: true,
    is_enabled: true,
    time_limit_minutes: 30,
    total_marks: 25,
    question_count: 10,
    pdf_url: '/downloads/class5_free_diagnostic.pdf',
    has_answer_key: true,
    has_step_by_step_solutions: true,
    has_hints: true,
    sort_order: 2,
  },
  {
    id: 'cnt_5_1_mcq',
    class_id: 'class_5',
    subject_id: 'subj_5_math',
    chapter_id: 'ch_5_1',
    content_type: 'mcq',
    title: 'Speed Math Quiz: Place Value Sprint (20 Questions)',
    description: 'Interactive multiple choice quiz with instant scoring and explanation popups.',
    difficulty: 'medium',
    access_type: 'package_restricted',
    package_ids: ['pkg_pro', 'pkg_basic', 'pkg_school'],
    is_published: true,
    is_enabled: true,
    time_limit_minutes: 20,
    total_marks: 20,
    question_count: 20,
    has_answer_key: true,
    has_step_by_step_solutions: true,
    has_hints: true,
    sort_order: 3,
  },
  {
    id: 'cnt_5_4_pp1',
    class_id: 'class_5',
    subject_id: 'subj_5_math',
    chapter_id: 'ch_5_4',
    content_type: 'practice_paper',
    title: 'Master Assessment: Fractions, Parts & Wholes',
    description: 'Comprehensive assessment paper covering proper, improper, mixed fractions and shaded area representation.',
    difficulty: 'hard',
    access_type: 'package_restricted',
    package_ids: ['pkg_pro', 'pkg_school'],
    is_published: true,
    is_enabled: true,
    time_limit_minutes: 60,
    total_marks: 60,
    question_count: 18,
    pdf_url: '/downloads/class5_fractions_master.pdf',
    has_answer_key: true,
    has_step_by_step_solutions: true,
    has_hints: true,
    sort_order: 4,
  },
  {
    id: 'cnt_5_7_olympiad',
    class_id: 'class_5',
    subject_id: 'subj_5_olympiad',
    chapter_id: 'ch_5_7',
    content_type: 'practice_paper',
    title: 'IMO Olympiad Mock Test 1: Advanced Logical Reasoning',
    description: 'High-order thinking skills (HOTS), pattern deductions, and non-routine problem solving.',
    difficulty: 'olympiad',
    access_type: 'package_restricted',
    package_ids: ['pkg_pro', 'pkg_school'],
    is_published: true,
    is_enabled: true,
    time_limit_minutes: 60,
    total_marks: 50,
    question_count: 25,
    pdf_url: '/downloads/class5_olympiad_mock1.pdf',
    has_answer_key: true,
    has_step_by_step_solutions: true,
    has_hints: true,
    sort_order: 5,
  },
];

export const INITIAL_PACKAGES: PackageItem[] = [
  {
    id: 'pkg_free',
    code: 'FREE_TRIAL',
    name: 'Free Trial / Starter',
    priceINR: 0,
    priceUSD: 0,
    validityDays: 14,
    eligibleClassIds: ['class_1', 'class_2', 'class_3', 'class_4', 'class_5', 'class_6', 'class_7', 'class_8'],
    description: 'Introductory preview with sample practice papers across all 8 grades.',
    isEnabled: true,
    practicePaperLimit: 5,
    customPaperLimit: 1,
    targetAudience: 'New Students & Parents',
    features: {
      allCurriculumAccess: false,
      practicePapers: true,
      detailedStepSolutions: true,
      pdfDownload: true,
      mcqs: true,
      flashCards: true,
      customPapers: false,
      aiFeatures: false,
      analyticsDashboard: false,
      teacherBranding: false,
      batchManagement: false,
      prioritySupport: false,
    },
  },
  {
    id: 'pkg_basic',
    code: 'CORE_FOUNDATION',
    name: 'Core Foundations Pass',
    priceINR: 749,
    priceUSD: 12,
    validityDays: 180,
    eligibleClassIds: ['class_1', 'class_2', 'class_3', 'class_4', 'class_5', 'class_6', 'class_7', 'class_8'],
    description: '6-Month unlimited access to syllabus practice papers and solutions.',
    isEnabled: true,
    practicePaperLimit: 80,
    customPaperLimit: 15,
    targetAudience: 'Class 1 to 8 Students',
    features: {
      allCurriculumAccess: true,
      practicePapers: true,
      detailedStepSolutions: true,
      pdfDownload: true,
      mcqs: true,
      flashCards: true,
      customPapers: true,
      aiFeatures: false,
      analyticsDashboard: true,
      teacherBranding: false,
      batchManagement: false,
      prioritySupport: false,
    },
  },
  {
    id: 'pkg_pro',
    code: 'OLYMPIAD_PRO',
    name: 'Olympiad & Complete Math Mastery',
    priceINR: 1499,
    priceUSD: 24,
    validityDays: 365,
    eligibleClassIds: ['class_1', 'class_2', 'class_3', 'class_4', 'class_5', 'class_6', 'class_7', 'class_8'],
    description: '1-Year full platform access including Olympiad papers, unlimited custom test generator, and AI explainer.',
    isEnabled: true,
    practicePaperLimit: -1,
    customPaperLimit: -1,
    targetAudience: 'Ambitious Students & Top Rankers',
    features: {
      allCurriculumAccess: true,
      practicePapers: true,
      detailedStepSolutions: true,
      pdfDownload: true,
      mcqs: true,
      flashCards: true,
      customPapers: true,
      aiFeatures: true,
      analyticsDashboard: true,
      teacherBranding: false,
      batchManagement: false,
      prioritySupport: true,
    },
  },
  {
    id: 'pkg_school',
    code: 'INSTITUTE_ENTERPRISE',
    name: 'School & Teacher Multi-Student Suite',
    priceINR: 4999,
    priceUSD: 79,
    validityDays: 365,
    eligibleClassIds: ['class_1', 'class_2', 'class_3', 'class_4', 'class_5', 'class_6', 'class_7', 'class_8'],
    description: 'Batch roster management, custom printable watermark with school logo, and bulk question exports.',
    isEnabled: true,
    practicePaperLimit: -1,
    customPaperLimit: -1,
    targetAudience: 'Schools, Tutors & Coaching Centers',
    features: {
      allCurriculumAccess: true,
      practicePapers: true,
      detailedStepSolutions: true,
      pdfDownload: true,
      mcqs: true,
      flashCards: true,
      customPapers: true,
      aiFeatures: true,
      analyticsDashboard: true,
      teacherBranding: true,
      batchManagement: true,
      prioritySupport: true,
    },
  },
];

export const INITIAL_STUDENTS: Student[] = [
  {
    id: 'stu_1',
    name: 'Aarav Sharma',
    email: 'aarav.sharma@gmail.com',
    mobile: '+91 98765 43210',
    classId: 'class_5',
    board: 'CBSE',
    packageId: 'pkg_pro',
    packageName: 'Olympiad & Complete Math Mastery',
    packageStatus: 'active',
    purchaseDate: '2026-06-15',
    expiryDate: '2027-06-15',
    paymentStatus: 'successful',
    accountStatus: 'active',
    lastLogin: '2026-08-16 19:40',
    customPaperCountUsed: 8,
    customPaperLimit: -1,
    createdAt: '2026-06-15',
  },
  {
    id: 'stu_2',
    name: 'Ananya Verma',
    email: 'ananya.v@outlook.com',
    mobile: '+91 98123 45678',
    classId: 'class_6',
    board: 'ICSE',
    packageId: 'pkg_basic',
    packageName: 'Core Foundations Pass',
    packageStatus: 'active',
    purchaseDate: '2026-07-01',
    expiryDate: '2026-12-31',
    paymentStatus: 'successful',
    accountStatus: 'active',
    lastLogin: '2026-08-15 16:20',
    customPaperCountUsed: 4,
    customPaperLimit: 15,
    createdAt: '2026-07-01',
  },
  {
    id: 'stu_3',
    name: 'Rohan Deshmukh',
    email: 'rohan.d@yahoo.in',
    mobile: '+91 97654 32109',
    classId: 'class_7',
    board: 'State Board',
    packageId: 'pkg_pro',
    packageName: 'Olympiad & Complete Math Mastery',
    packageStatus: 'expired',
    purchaseDate: '2025-08-01',
    expiryDate: '2026-08-01',
    paymentStatus: 'successful',
    accountStatus: 'active',
    lastLogin: '2026-08-10 11:30',
    customPaperCountUsed: 35,
    customPaperLimit: -1,
    createdAt: '2025-08-01',
  },
  {
    id: 'stu_4',
    name: 'Diya Patel',
    email: 'diya.patel@gmail.com',
    mobile: '+91 99887 76655',
    classId: 'class_4',
    board: 'CBSE',
    packageId: 'pkg_free',
    packageName: 'Free Trial / Starter',
    packageStatus: 'active',
    purchaseDate: '2026-08-10',
    expiryDate: '2026-08-24',
    paymentStatus: 'successful',
    accountStatus: 'active',
    lastLogin: '2026-08-16 14:10',
    customPaperCountUsed: 1,
    customPaperLimit: 1,
    createdAt: '2026-08-10',
  },
];

export const INITIAL_PAYMENTS: PaymentTransaction[] = [
  {
    id: 'txn_101',
    studentId: 'stu_1',
    studentName: 'Aarav Sharma',
    studentEmail: 'aarav.sharma@gmail.com',
    studentMobile: '+91 98765 43210',
    orderId: 'ORD_2026_98214',
    packageId: 'pkg_pro',
    packageName: 'Olympiad & Complete Math Mastery',
    classId: 'class_5',
    amount: 1499,
    currency: 'INR',
    paymentGateway: 'Razorpay',
    paymentMethod: 'UPI (Google Pay)',
    status: 'successful',
    paymentDate: '2026-06-15 14:32',
    transactionId: 'pay_RZP_991823719',
    packageActivationDate: '2026-06-15',
    packageExpiryDate: '2027-06-15',
    invoiceNumber: 'INV-2026-00412',
  },
  {
    id: 'txn_102',
    studentId: 'stu_2',
    studentName: 'Ananya Verma',
    studentEmail: 'ananya.v@outlook.com',
    studentMobile: '+91 98123 45678',
    orderId: 'ORD_2026_99341',
    packageId: 'pkg_basic',
    packageName: 'Core Foundations Pass',
    classId: 'class_6',
    amount: 749,
    currency: 'INR',
    paymentGateway: 'Razorpay',
    paymentMethod: 'Netbanking (HDFC)',
    status: 'successful',
    paymentDate: '2026-07-01 10:15',
    transactionId: 'pay_RZP_118239012',
    packageActivationDate: '2026-07-01',
    packageExpiryDate: '2026-12-31',
    invoiceNumber: 'INV-2026-00523',
  },
  {
    id: 'txn_103',
    studentId: 'stu_3',
    studentName: 'Rohan Deshmukh',
    studentEmail: 'rohan.d@yahoo.in',
    studentMobile: '+91 97654 32109',
    orderId: 'ORD_2026_99499',
    packageId: 'pkg_pro',
    packageName: 'Olympiad & Complete Math Mastery',
    classId: 'class_7',
    amount: 1499,
    currency: 'INR',
    paymentGateway: 'UPI',
    paymentMethod: 'Direct QR Code',
    status: 'pending',
    paymentDate: '2026-08-16 18:20',
    transactionId: 'UPI_REF_9912830182',
    packageActivationDate: '2026-08-16',
    packageExpiryDate: '2027-08-16',
    invoiceNumber: 'INV-2026-00781',
  },
];

export const INITIAL_DASHBOARD_CONFIG: DashboardFeatureConfig = {
  practicePapers: true,
  questionBank: true,
  mcqs: true,
  flashCards: true,
  notes: true,
  previousPapers: true,
  solutions: true,
  progress: true,
  reports: true,
  downloads: true,
  customPracticePaper: true,
  notifications: true,
  announcements: true,
  aiTutor: true,
};

export const INITIAL_GLOBAL_SETTINGS: GlobalWebsiteSettings = {
  siteName: 'Beyond Classroom',
  siteTagline: 'Empowering Class 1 to 8 Mathematics Excellence',
  metaDescription: 'India’s most trusted K-8 mathematics platform with curated worksheets, step-by-step solutions, and Olympiad mastery sets.',
  supportEmail: 'support@beyondclassroom.in',
  supportPhone: '+91 80 4718 9000',
  supportAddress: 'Beyond Classroom EdTech Campus, Indiranagar, Bengaluru, Karnataka 560038',
  maintenanceMode: {
    isEnabled: false,
    title: 'Scheduled Platform Optimization',
    message: 'We are upgrading our question bank and solution engines. Platform will be back online shortly.',
    expectedAvailability: 'Today at 11:00 PM IST',
  },
};

export const INITIAL_ANNOUNCEMENTS: AnnouncementItem[] = [
  {
    id: 'ann_1',
    title: 'National Mathematics Olympiad (IMO 2026) Mock Series Released',
    content: 'Specialized high-order Olympiad practice sets are now live for Class 3 through Class 8 students.',
    targetAudience: 'all',
    priority: 'high',
    isPublished: true,
    publishDate: '2026-08-15',
    author: 'Beyond Classroom Academic Council',
  },
  {
    id: 'ann_2',
    title: 'Class 5 Fractions & Decimals Concept Mastery Sprint',
    content: 'New animated hints and step-by-step proofs added to Chapter 4 (Parts & Wholes).',
    targetAudience: 'class',
    targetClassId: 'class_5',
    priority: 'normal',
    isPublished: true,
    publishDate: '2026-08-12',
    author: 'Dr. Sarah Jenkins',
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif_1',
    studentId: 'stu_1',
    title: 'New Practice Paper Unlocked',
    message: 'Chapter 5: Tenths and Hundredths Practice Set 2 is now ready for your Class 5 track.',
    type: 'info',
    isRead: false,
    date: '2026-08-16 15:00',
  },
  {
    id: 'notif_2',
    studentId: 'stu_3',
    title: 'Subscription Expiry Notice',
    message: 'Your Olympiad & Complete Math Mastery Pass expired on Aug 1. Renew to restore download access.',
    type: 'warning',
    isRead: false,
    date: '2026-08-10 09:00',
  },
];

export const INITIAL_AUDIT_LOGS: AdminActivityLog[] = [
  {
    id: 'log_1',
    adminId: 'adm_1',
    adminName: 'Super Administrator',
    adminRole: 'super_admin',
    action: 'Student Override Configured',
    entity: 'Student Management',
    details: 'Enabled custom paper generator override for Aarav Sharma (stu_1)',
    ipAddress: '103.21.124.5',
    timestamp: '2026-08-16 21:12:40',
  },
  {
    id: 'log_2',
    adminId: 'adm_2',
    adminName: 'Dr. Sarah Jenkins',
    adminRole: 'content_admin',
    action: 'Practice Paper Published',
    entity: 'Content Repository',
    details: 'Published Practice Paper 1 for Class 5 Chapter 1',
    ipAddress: '122.162.88.19',
    timestamp: '2026-08-16 18:45:10',
  },
];

export const INITIAL_EDUCATIONAL_CONTENT: EducationalContent[] = INITIAL_CONTENTS;
export const INITIAL_ACTIVITY_LOGS: AdminActivityLog[] = INITIAL_AUDIT_LOGS;

