import {
  AcademicClass,
  AcademicSubject,
  AcademicChapter,
  EducationalContent,
  PackageItem,
  Student,
  PaymentTransaction,
  DashboardFeatureConfig,
  GlobalWebsiteSettings,
  AnnouncementItem,
  NotificationItem,
  AdminUser,
  AdminActivityLog,
} from '../types/admin';
import { WorksheetRequest, PracticeQuizAttempt } from '../types/student';

export const INITIAL_ADMIN_USERS: AdminUser[] = [
  {
    id: 'adm_1',
    name: 'Super Administrator',
    email: 'admin@beyondclassroom.com',
    role: 'super_admin',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
    isEnabled: true,
    twoFactorEnabled: true,
    lastLogin: '2026-08-16 21:30',
    createdAt: '2025-01-10',
    permissions: ['all'],
  },
  {
    id: 'adm_2',
    name: 'Dr. Sarah Jenkins',
    email: 'content@beyondclassroom.com',
    role: 'content_admin',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=120&auto=format&fit=crop&q=80',
    isEnabled: true,
    twoFactorEnabled: false,
    lastLogin: '2026-08-16 18:45',
    createdAt: '2025-02-15',
    permissions: ['content_manage', 'curriculum_edit', 'papers_publish'],
  },
  {
    id: 'adm_3',
    name: 'Vikram Malhotra',
    email: 'support@beyondclassroom.com',
    role: 'support_admin',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80',
    isEnabled: true,
    twoFactorEnabled: false,
    lastLogin: '2026-08-16 19:15',
    createdAt: '2025-03-01',
    permissions: ['student_support', 'payments_view', 'access_override_request'],
  },
];

export const INITIAL_CLASSES: AcademicClass[] = [
  { id: 'class_1', gradeNumber: 1, name: 'Class 1 Mathematics', shortName: 'Class 1', isEnabled: true, sortOrder: 1, description: 'Foundational Numbers, Counting, Shapes, Basic Addition & Subtraction' },
  { id: 'class_2', gradeNumber: 2, name: 'Class 2 Mathematics', shortName: 'Class 2', isEnabled: true, sortOrder: 2, description: '2-digit arithmetic, Place value, Basic Measurement, Simple Word Problems' },
  { id: 'class_3', gradeNumber: 3, name: 'Class 3 Mathematics', shortName: 'Class 3', isEnabled: true, sortOrder: 3, description: 'Multiplication Tables, Division Intro, Fractions Basics, Geometry' },
  { id: 'class_4', gradeNumber: 4, name: 'Class 4 Mathematics', shortName: 'Class 4', isEnabled: true, sortOrder: 4, description: 'Factors & Multiples, Decimals, Perimeter & Area, Time & Money' },
  { id: 'class_5', gradeNumber: 5, name: 'Class 5 Mathematics', shortName: 'Class 5', isEnabled: true, sortOrder: 5, description: 'Large Numbers, Operations, Fractions, Decimals, Geometry, Data Handling' },
  { id: 'class_6', gradeNumber: 6, name: 'Class 6 Mathematics', shortName: 'Class 6', isEnabled: true, sortOrder: 6, description: 'Integers, Algebra Intro, Ratio & Proportion, Mensuration, Practical Geometry' },
  { id: 'class_7', gradeNumber: 7, name: 'Class 7 Mathematics', shortName: 'Class 7', isEnabled: true, sortOrder: 7, description: 'Lines & Angles, Triangles, Rational Numbers, Algebraic Expressions, Exponents' },
  { id: 'class_8', gradeNumber: 8, name: 'Class 8 Mathematics', shortName: 'Class 8', isEnabled: true, sortOrder: 8, description: 'Linear Equations, Quadrilaterals, Squares & Roots, Factorisation, Mensuration' },
];

export const INITIAL_SUBJECTS: AcademicSubject[] = [
  { id: 'subj_1_math', classId: 'class_1', name: 'Core Mathematics', code: 'MTH_01', isEnabled: true, sortOrder: 1, description: 'Numbers & Shapes' },
  { id: 'subj_1_mental', classId: 'class_1', name: 'Speed & Mental Math', code: 'MNT_01', isEnabled: true, sortOrder: 2, description: 'Visual calculation tricks' },
  { id: 'subj_2_math', classId: 'class_2', name: 'Core Mathematics', code: 'MTH_02', isEnabled: true, sortOrder: 1 },
  { id: 'subj_2_mental', classId: 'class_2', name: 'Mental Math & Reasoning', code: 'MNT_02', isEnabled: true, sortOrder: 2 },
  { id: 'subj_3_math', classId: 'class_3', name: 'Core Mathematics', code: 'MTH_03', isEnabled: true, sortOrder: 1 },
  { id: 'subj_4_math', classId: 'class_4', name: 'Core Mathematics', code: 'MTH_04', isEnabled: true, sortOrder: 1 },
  { id: 'subj_5_math', classId: 'class_5', name: 'Core Mathematics', code: 'MTH_05', isEnabled: true, sortOrder: 1, description: 'NCERT / CBSE / ICSE Standard' },
  { id: 'subj_5_olympiad', classId: 'class_5', name: 'Math Olympiad & IMO Prep', code: 'OLY_05', isEnabled: true, sortOrder: 2, description: 'Competitive problems & logic' },
  { id: 'subj_6_math', classId: 'class_6', name: 'Core Mathematics', code: 'MTH_06', isEnabled: true, sortOrder: 1 },
  { id: 'subj_6_olympiad', classId: 'class_6', name: 'Olympiad & Reasoning', code: 'OLY_06', isEnabled: true, sortOrder: 2 },
  { id: 'subj_7_math', classId: 'class_7', name: 'Core Mathematics', code: 'MTH_07', isEnabled: true, sortOrder: 1 },
  { id: 'subj_8_math', classId: 'class_8', name: 'Core Mathematics', code: 'MTH_08', isEnabled: true, sortOrder: 1 },
  { id: 'subj_8_applied', classId: 'class_8', name: 'Applied Math & Geometry', code: 'APP_08', isEnabled: true, sortOrder: 2 },
];

export const INITIAL_CHAPTERS: AcademicChapter[] = [
  // Class 5 Chapters
  { id: 'ch_5_1', classId: 'class_5', subjectId: 'subj_5_math', chapterNumber: 1, title: 'The Fish Tale (Large Numbers & Place Value)', description: 'Place values up to Crores, Indian and International system, Real-life word problems.', isEnabled: true, sortOrder: 1 },
  { id: 'ch_5_2', classId: 'class_5', subjectId: 'subj_5_math', chapterNumber: 2, title: 'Shapes and Angles (Geometry)', description: 'Acute, Obtuse, Right angles, Degree clock, Protractor measurements.', isEnabled: true, sortOrder: 2 },
  { id: 'ch_5_3', classId: 'class_5', subjectId: 'subj_5_math', chapterNumber: 3, title: 'How Many Squares? (Area & Perimeter)', description: 'Grid area calculations, Irregular shapes, Formula for Rectangle and Square.', isEnabled: true, sortOrder: 3 },
  { id: 'ch_5_4', classId: 'class_5', subjectId: 'subj_5_math', chapterNumber: 4, title: 'Parts and Wholes (Fractions)', description: 'Proper, Improper, Mixed fractions, Equivalent fractions and addition.', isEnabled: true, sortOrder: 4 },
  { id: 'ch_5_5', classId: 'class_5', subjectId: 'subj_5_math', chapterNumber: 5, title: 'Tenths and Hundredths (Decimals)', description: 'Decimal place value, Conversion between Fractions and Decimals, Money arithmetic.', isEnabled: true, sortOrder: 5 },
  { id: 'ch_5_6', classId: 'class_5', subjectId: 'subj_5_math', chapterNumber: 6, title: 'Boxes and Sketches (3D & Spatial)', description: 'Nets of cube, 2D representations of 3D objects, isometric perspectives.', isEnabled: true, sortOrder: 6 },
  { id: 'ch_5_7', classId: 'class_5', subjectId: 'subj_5_olympiad', chapterNumber: 1, title: 'Logical Reasoning & Pattern Analysis', description: 'Number series, geometric puzzles, coding-decoding for Olympiads.', isEnabled: true, sortOrder: 1 },

  // Class 6 Chapters
  { id: 'ch_6_1', classId: 'class_6', subjectId: 'subj_6_math', chapterNumber: 1, title: 'Knowing Our Numbers', description: 'Comparing large numbers, Estimation, Roman numerals.', isEnabled: true, sortOrder: 1 },
  { id: 'ch_6_2', classId: 'class_6', subjectId: 'subj_6_math', chapterNumber: 2, title: 'Whole Numbers & Properties', description: 'Closure, Commutative, Associative and Distributive laws.', isEnabled: true, sortOrder: 2 },
  { id: 'ch_6_3', classId: 'class_6', subjectId: 'subj_6_math', chapterNumber: 3, title: 'Playing with Numbers (Factors & Multiples)', description: 'Prime factorization, HCF, LCM, Divisibility rules.', isEnabled: true, sortOrder: 3 },
  { id: 'ch_6_4', classId: 'class_6', subjectId: 'subj_6_math', chapterNumber: 4, title: 'Integers on the Number Line', description: 'Positive and negative numbers, Addition and subtraction of integers.', isEnabled: true, sortOrder: 4 },
  { id: 'ch_6_5', classId: 'class_6', subjectId: 'subj_6_math', chapterNumber: 5, title: 'Algebra: Introduction to Variables', description: 'Variables in expressions, Equations and standard solutions.', isEnabled: true, sortOrder: 5 },

  // Class 7 Chapters
  { id: 'ch_7_1', classId: 'class_7', subjectId: 'subj_7_math', chapterNumber: 1, title: 'Integers & Arithmetic Laws', description: 'Multiplication & division of negative numbers, BODMAS.', isEnabled: true, sortOrder: 1 },
  { id: 'ch_7_2', classId: 'class_7', subjectId: 'subj_7_math', chapterNumber: 2, title: 'Fractions and Decimals Mastery', description: 'Multiplication & division of fractional quantities.', isEnabled: true, sortOrder: 2 },
  { id: 'ch_7_3', classId: 'class_7', subjectId: 'subj_7_math', chapterNumber: 3, title: 'Simple Equations', description: 'Transposition method, word problem formulations.', isEnabled: true, sortOrder: 3 },

  // Class 8 Chapters
  { id: 'ch_8_1', classId: 'class_8', subjectId: 'subj_8_math', chapterNumber: 1, title: 'Rational Numbers & Number Line Properties', description: 'Density property, additive and multiplicative inverse.', isEnabled: true, sortOrder: 1 },
  { id: 'ch_8_2', classId: 'class_8', subjectId: 'subj_8_math', chapterNumber: 2, title: 'Linear Equations in One Variable', description: 'Equations with variables on both sides, age and speed problems.', isEnabled: true, sortOrder: 2 },
  { id: 'ch_8_3', classId: 'class_8', subjectId: 'subj_8_math', chapterNumber: 3, title: 'Understanding Quadrilaterals & Polygons', description: 'Angle sum property, Parallelograms, Rhombus, Trapezius theorems.', isEnabled: true, sortOrder: 3 },
  { id: 'ch_8_4', classId: 'class_8', subjectId: 'subj_8_math', chapterNumber: 4, title: 'Squares and Square Roots', description: 'Prime factorization method, Long division square roots.', isEnabled: true, sortOrder: 4 },
];

export const INITIAL_CONTENTS: EducationalContent[] = [
  // Class 5 Chapter 1 Notes (PDF)
  {
    id: 'cnt_5_1_notes',
    class_id: 'class_5',
    subject_id: 'subj_5_math',
    chapter_id: 'ch_5_1',
    content_type: 'notes',
    title: 'Chapter 1: The Fish Tale — Complete Concept Notes & Formula Sheet (PDF)',
    description: 'Comprehensive study material covering Indian & International place value system, expanded forms, speed-distance-time word problems, and currency arithmetic.',
    difficulty: 'easy',
    access_type: 'free',
    package_ids: ['pkg_free', 'pkg_pro', 'pkg_basic', 'pkg_school'],
    is_published: true,
    is_enabled: true,
    time_limit_minutes: 20,
    total_marks: 0,
    question_count: 0,
    pdf_url: '/documents/class5_ch1_concept_notes.pdf',
    pdf_filename: 'Class5_Math_Ch1_FishTale_Notes.pdf',
    pdf_pages_count: 4,
    pdf_file_size: '2.4 MB',
    disable_download: true,
    key_summary_points: [
      '1 Lakh = 100 Thousands = 1,00,000 (5 Zeroes)',
      '1 Crore = 100 Lakhs = 10 Millions = 1,00,00,000 (7 Zeroes)',
      'Indian System Period Grouping: 3, 2, 2 digits (Ones, Thousands, Lakhs, Crores)',
      'International System Period Grouping: 3, 3, 3 digits (Ones, Thousands, Millions)',
      'Speed = Distance ÷ Time | Total Cost = Quantity × Rate per kg',
    ],
    pdf_pages_content: [
      {
        pageNumber: 1,
        heading: 'Unit 1: Large Numbers & Number Systems',
        subheading: 'Concept Breakdown & Visual Place Value Charts',
        text: 'In Grade 5 Mathematics, we transition from thousands into large quantities like Lakhs (1,00,000) and Crores (1,00,00,000). Mastering the grouping of digits via periods is vital for error-free reading and computation.',
        keyPoints: [
          'Indian System: Grouped as [Crores] , [Ten Lakh, Lakh] , [Ten Thousand, Thousand] , [Hundreds, Tens, Ones]. Example: 4,32,15,670.',
          'International System: Grouped strictly in triads [Millions] , [Thousands] , [Ones]. Example: 43,215,670 (Forty-three million two hundred fifteen thousand six hundred seventy).',
          'Comparison Rule: 1 Million = 10 Lakhs | 10 Millions = 1 Crore | 100 Millions = 10 Crores.',
        ],
        formulaHighlight: 'Number of Zeroes Cheat Sheet: Thousand = 3 zeroes | Lakh = 5 zeroes | Million = 6 zeroes | Crore = 7 zeroes',
        exampleQuestion: {
          question: 'Write 8,75,95,762 in words according to both Indian and International Numeration Systems.',
          stepSolution: '1. Indian: 8,75,95,762 = Eight crore seventy-five lakh ninety-five thousand seven hundred sixty-two.\n2. International: Group as 87,595,762 = Eighty-seven million five hundred ninety-five thousand seven hundred sixty-two.',
          answer: 'Indian: 8,75,95,762 | International: 87,595,762',
        },
      },
      {
        pageNumber: 2,
        heading: 'Unit 2: Real-World Arithmetic (Speed, Distance, Time)',
        subheading: 'Applied Word Problems & Fisherman Boat Analytics',
        text: 'Large numbers are frequently applied to calculate travel distances, fishing catch quantities, and commercial fish drying factory revenues.',
        keyPoints: [
          'Log Boat Speed: A simple log boat travels ~4 km in 1 hour.',
          'Motor Boat Speed: A modern motor boat travels ~20 km in 1 hour.',
          'Time required = Total Distance ÷ Speed in 1 hour.',
          'Catch Yield: A machine boat can catch up to 6,000 kg of fish in one trip.',
        ],
        formulaHighlight: 'Core Formula: Distance = Speed × Time  |  Time = Distance / Speed  |  Speed = Distance / Time',
        exampleQuestion: {
          question: 'If a motor boat travels at a speed of 20 km per hour, how far can it go in three and a half hours (3.5 hours)?',
          stepSolution: 'Step 1: Speed = 20 km/h\nStep 2: Time = 3.5 hours\nStep 3: Distance = Speed × Time = 20 × 3.5 = 70 km.',
          answer: '70 Kilometers',
        },
      },
      {
        pageNumber: 3,
        heading: 'Unit 3: Financial Math & Bank Loans',
        subheading: 'Savings Groups, Interest Calculations & Profits',
        text: 'Understanding practical banking scenarios: saving money in women cooperative banks (Meenkar Bank), loan repayments, and monthly installments.',
        keyPoints: [
          'Total Money Repaid = Monthly Installment × Number of Months.',
          'Total Interest Paid = Total Money Repaid - Principal Loan Amount.',
          'Cost of Fresh Fish vs Dried Fish: When fresh fish is dried, it becomes 1/3 of its original weight.',
        ],
        formulaHighlight: 'Fresh Fish to Dried Fish: 1 kg Dried Fish = 3 kg Fresh Fish (Weight reduces to 1/3rd upon drying)',
        exampleQuestion: {
          question: 'Gracy took a loan of ₹4,000 to buy a net. She paid back ₹345 every month for one year. How much total money did she pay back to the bank?',
          stepSolution: 'Step 1: 1 Year = 12 Months\nStep 2: Monthly Payment = ₹345\nStep 3: Total Repaid = 345 × 12 = ₹4,140\nStep 4: Interest paid = 4,140 - 4,000 = ₹140.',
          answer: 'Total Repaid = ₹4,140 (Interest = ₹140)',
        },
      },
      {
        pageNumber: 4,
        heading: 'Unit 4: Chapter Summary & Golden Revision Rules',
        subheading: 'Quick Flash Review for Exams & Olympiads',
        text: 'Review these fundamental axioms before attempting practice worksheets or speed tests.',
        keyPoints: [
          'Always insert commas from the right: In Indian system, first 3 digits then every 2 digits.',
          'In word problems, align your units (hours to minutes, grams to kilograms) before multiplying.',
          'Double-check calculations when multiplying by multiples of 10, 100, 1000 by shifting zeroes.',
        ],
        formulaHighlight: 'Key Takeaway: 1 Million = 10 Lakhs | 1 Billion = 100 Crores | 1 Tonne = 1,000 kg',
      },
    ],
    has_answer_key: true,
    has_step_by_step_solutions: true,
    has_hints: true,
    sort_order: 1,
  },

  // Class 5 Chapter 2 Notes (PDF)
  {
    id: 'cnt_5_2_notes',
    class_id: 'class_5',
    subject_id: 'subj_5_math',
    chapter_id: 'ch_5_2',
    content_type: 'notes',
    title: 'Chapter 2: Shapes & Angles — Complete Geometry Notes (PDF)',
    description: 'Visual study guide covering Right Angles (90°), Acute & Obtuse angles, Angle testers, Degree Clock, and Polygon Vertices.',
    difficulty: 'medium',
    access_type: 'package_restricted',
    package_ids: ['pkg_pro', 'pkg_basic', 'pkg_school'],
    is_published: true,
    is_enabled: true,
    time_limit_minutes: 25,
    total_marks: 0,
    question_count: 0,
    pdf_url: '/documents/class5_ch2_geometry_notes.pdf',
    pdf_filename: 'Class5_Math_Ch2_Shapes_Angles_Notes.pdf',
    pdf_pages_count: 3,
    pdf_file_size: '1.9 MB',
    disable_download: true,
    key_summary_points: [
      'Right Angle = Exactly 90° (Forms an "L" shape)',
      'Acute Angle = Less than 90° (Narrower than an L shape)',
      'Obtuse Angle = Greater than 90° and less than 180°',
      'Straight Angle = Exactly 180°',
      'Degree Clock: Full turn = 360°, Half turn = 180°, Quarter turn = 90°',
    ],
    pdf_pages_content: [
      {
        pageNumber: 1,
        heading: 'Geometry Fundamentals: Angle Types & Classifications',
        subheading: 'Understanding Rays, Vertices, and Angle Measurements',
        text: 'An angle is created when two straight lines or rays meet at a common point called the vertex. The opening between the lines determines the angle magnitude measured in degrees (°).',
        keyPoints: [
          'Right Angle (90°): Corner of a book, window edge, table leg.',
          'Acute Angle (< 90°): Open pair of scissors, letter V, slice of pizza.',
          'Obtuse Angle (> 90°): Open laptop lid, reclining chair backrest.',
        ],
        formulaHighlight: 'Angle Classification: Acute (< 90°) < Right (90°) < Obtuse (90° - 180°) < Straight (180°)',
      },
      {
        pageNumber: 2,
        heading: 'Angles in Time: The Degree Clock',
        subheading: 'Clock Hand Angles & Rotations',
        text: 'A circular clock represents a 360° rotation divided into 12 equal hours. Each 1-hour step on the dial equals exactly 30° (360° ÷ 12 = 30°).',
        keyPoints: [
          'At 3:00 and 9:00: Hands form exactly 90° (Right Angle).',
          'At 6:00: Hands form exactly 180° (Straight Angle).',
          'At 2:00: Hands form 2 × 30° = 60° (Acute Angle).',
          'At 4:00: Hands form 4 × 30° = 120° (Obtuse Angle).',
        ],
        formulaHighlight: 'Clock Hand Formula: Angle per hour step = 30° | Angle per minute step = 6° (360° / 60)',
      },
      {
        pageNumber: 3,
        heading: 'Polygons, Matchstick Puzzles & Angle Testers',
        subheading: 'Closed vs Open Shapes & Structural Rigidity',
        text: 'A polygon is a 2D closed shape made with straight lines. Changing the angles between sides changes the shape even if the side lengths remain identical.',
        keyPoints: [
          'Triangles are rigid: Triangles cannot change angle without changing side length (Used in bridges & cranes).',
          'Squares & Pentagons can deform: Their corner angles can shift into rhombuses unless diagonal braces are added.',
        ],
        formulaHighlight: 'Golden Rule: Sum of interior angles in a Triangle is always 180° | In a Quadrilateral is 360°',
      },
    ],
    has_answer_key: true,
    has_step_by_step_solutions: true,
    has_hints: true,
    sort_order: 2,
  },

  // Class 5 Chapter 4 Notes (PDF)
  {
    id: 'cnt_5_4_notes',
    class_id: 'class_5',
    subject_id: 'subj_5_math',
    chapter_id: 'ch_5_4',
    content_type: 'notes',
    title: 'Chapter 4: Parts & Wholes (Fractions Mastery) — Study Material (PDF)',
    description: 'Illustrated guide on proper fractions, improper fractions, mixed numbers, equivalent fractions, and visual shaded fraction grids.',
    difficulty: 'medium',
    access_type: 'package_restricted',
    package_ids: ['pkg_pro', 'pkg_school'],
    is_published: true,
    is_enabled: true,
    time_limit_minutes: 30,
    total_marks: 0,
    question_count: 0,
    pdf_url: '/documents/class5_ch4_fractions_notes.pdf',
    pdf_filename: 'Class5_Math_Ch4_Fractions_Study_Material.pdf',
    pdf_pages_count: 3,
    pdf_file_size: '2.1 MB',
    disable_download: true,
    key_summary_points: [
      'Numerator = Number of parts taken | Denominator = Total equal parts in whole',
      'Proper Fraction: Numerator < Denominator (e.g. 3/4)',
      'Improper Fraction: Numerator >= Denominator (e.g. 7/4)',
      'Equivalent Fractions: Multiplying or dividing both numerator & denominator by same non-zero number',
      'Simplest Form: Numerator and denominator share no common factors other than 1',
    ],
    pdf_pages_content: [
      {
        pageNumber: 1,
        heading: 'Understanding Fractions: Part of a Whole & Part of a Collection',
        subheading: 'Visual Breakdown of Fractional Parts',
        text: 'A fraction denotes an equal division of an object or group. When dividing a rectangular chocolate bar into 8 equal pieces, each piece is 1/8 of the whole.',
        keyPoints: [
          'Half (1/2), Quarter (1/4), Three-Fourths (3/4).',
          'The denominator must never be zero.',
          'Flag problem: The Indian Tricolour flag has 3 equal bands: Saffron (1/3), White (1/3), Green (1/3).',
        ],
        formulaHighlight: 'Fraction = Numerator (Parts Selected) / Denominator (Total Equal Parts)',
      },
      {
        pageNumber: 2,
        heading: 'Equivalent Fractions & Simplification',
        subheading: 'How to Find Equal Value Fractions',
        text: 'Different fractions can represent the exact same numerical quantity. 1/2 is the same portion as 2/4, 4/8, and 50/100.',
        keyPoints: [
          'To generate equivalent fractions: Multiply numerator and denominator by 2, 3, 4, etc.',
          'To reduce to simplest form: Divide by the Highest Common Factor (HCF).',
        ],
        formulaHighlight: 'Equivalent Rule: a/b = (a × k) / (b × k) where k ≠ 0',
      },
      {
        pageNumber: 3,
        heading: 'Addition & Subtraction with Like Denominators',
        subheading: 'Practical Word Problems & Fraction Strips',
        text: 'When denominators are identical, simply add or subtract the numerators while keeping the denominator constant.',
        keyPoints: [
          'Example: 2/7 + 3/7 = (2 + 3)/7 = 5/7.',
          'Whole number minus fraction: 1 - 3/5 = 5/5 - 3/5 = 2/5.',
        ],
        formulaHighlight: 'Addition Rule: (a/c) + (b/c) = (a + b)/c',
      },
    ],
    has_answer_key: true,
    has_step_by_step_solutions: true,
    has_hints: true,
    sort_order: 3,
  },

  // Class 6 Chapter 1 Notes (PDF)
  {
    id: 'cnt_6_1_notes',
    class_id: 'class_6',
    subject_id: 'subj_6_math',
    chapter_id: 'ch_6_1',
    content_type: 'notes',
    title: 'Class 6 Ch 1: Knowing Our Numbers — Advanced Notes & Formulas (PDF)',
    description: 'Comprehensive formulas for large numbers, estimation to nearest tens/hundreds, BODMAS brackets, and Roman numeral rules.',
    difficulty: 'medium',
    access_type: 'package_restricted',
    package_ids: ['pkg_pro', 'pkg_basic', 'pkg_school'],
    is_published: true,
    is_enabled: true,
    time_limit_minutes: 25,
    total_marks: 0,
    question_count: 0,
    pdf_url: '/documents/class6_ch1_numbers_notes.pdf',
    pdf_filename: 'Class6_Math_Ch1_KnowingNumbers_Notes.pdf',
    pdf_pages_count: 3,
    pdf_file_size: '2.0 MB',
    disable_download: true,
    key_summary_points: [
      'Roman Numerals: I=1, V=5, X=10, L=50, C=100, D=500, M=1000',
      'Roman symbols V, L, D are never repeated and never subtracted',
      'Estimation: If digit is < 5 round down, if >= 5 round up',
      'BODMAS: Brackets, Order, Division, Multiplication, Addition, Subtraction',
    ],
    pdf_pages_content: [
      {
        pageNumber: 1,
        heading: 'Large Numbers & Roman Numerals',
        subheading: 'Seven Fundamental Roman Symbols & Rules',
        text: 'The Roman numeration system uses 7 Latin letters to express any number up to thousands without a zero symbol.',
        keyPoints: [
          'Repetition rule: Only I, X, C, M can be repeated up to a maximum of 3 times consecutively.',
          'Subtraction rule: I can be subtracted from V and X only. X from L and C only. C from D and M only.',
        ],
        formulaHighlight: 'Roman Quick Map: IV = 4 | IX = 9 | XL = 40 | XC = 90 | CD = 400 | CM = 900',
      },
    ],
    has_answer_key: true,
    has_step_by_step_solutions: true,
    has_hints: true,
    sort_order: 4,
  },

  {
    id: 'cnt_5_1_pp1',
    class_id: 'class_5',
    subject_id: 'subj_5_math',
    chapter_id: 'ch_5_1',
    content_type: 'practice_paper',
    title: 'Practice Paper 1: Large Numbers, Place Value & Indian System',
    description: '15 Curated questions testing standard Indian vs International numeration, expanded form, and word problems.',
    difficulty: 'medium',
    access_type: 'package_restricted',
    package_ids: ['pkg_pro', 'pkg_basic', 'pkg_school'],
    is_published: true,
    is_enabled: true,
    time_limit_minutes: 45,
    total_marks: 50,
    question_count: 15,
    pdf_url: '/downloads/class5_ch1_paper1.pdf',
    has_answer_key: true,
    has_step_by_step_solutions: true,
    has_hints: true,
    sort_order: 1,
  },
  {
    id: 'cnt_5_1_free',
    class_id: 'class_5',
    subject_id: 'subj_5_math',
    chapter_id: 'ch_5_1',
    content_type: 'practice_paper',
    title: 'Free Diagnostic Sample: Class 5 Place Value & Arithmetic',
    description: 'Free sample paper accessible to all public visitors and unregistered users to experience Beyond Classroom quality.',
    difficulty: 'easy',
    access_type: 'free',
    package_ids: ['pkg_free', 'pkg_pro', 'pkg_basic', 'pkg_school'],
    is_published: true,
    is_enabled: true,
    time_limit_minutes: 30,
    total_marks: 25,
    question_count: 10,
    pdf_url: '/downloads/class5_free_diagnostic.pdf',
    has_answer_key: true,
    has_step_by_step_solutions: true,
    has_hints: true,
    sort_order: 2,
  },
  {
    id: 'cnt_5_1_mcq',
    class_id: 'class_5',
    subject_id: 'subj_5_math',
    chapter_id: 'ch_5_1',
    content_type: 'mcq',
    title: 'Speed Math Quiz: Place Value Sprint (20 Questions)',
    description: 'Interactive multiple choice quiz with instant scoring and explanation popups.',
    difficulty: 'medium',
    access_type: 'package_restricted',
    package_ids: ['pkg_pro', 'pkg_basic', 'pkg_school'],
    is_published: true,
    is_enabled: true,
    time_limit_minutes: 20,
    total_marks: 20,
    question_count: 20,
    has_answer_key: true,
    has_step_by_step_solutions: true,
    has_hints: true,
    sort_order: 3,
  },
  {
    id: 'cnt_5_4_pp1',
    class_id: 'class_5',
    subject_id: 'subj_5_math',
    chapter_id: 'ch_5_4',
    content_type: 'practice_paper',
    title: 'Master Assessment: Fractions, Parts & Wholes',
    description: 'Comprehensive assessment paper covering proper, improper, mixed fractions and shaded area representation.',
    difficulty: 'hard',
    access_type: 'package_restricted',
    package_ids: ['pkg_pro', 'pkg_school'],
    is_published: true,
    is_enabled: true,
    time_limit_minutes: 60,
    total_marks: 60,
    question_count: 18,
    pdf_url: '/downloads/class5_fractions_master.pdf',
    has_answer_key: true,
    has_step_by_step_solutions: true,
    has_hints: true,
    sort_order: 4,
  },
  {
    id: 'cnt_5_7_olympiad',
    class_id: 'class_5',
    subject_id: 'subj_5_olympiad',
    chapter_id: 'ch_5_7',
    content_type: 'practice_paper',
    title: 'IMO Olympiad Mock Test 1: Advanced Logical Reasoning',
    description: 'High-order thinking skills (HOTS), pattern deductions, and non-routine problem solving.',
    difficulty: 'olympiad',
    access_type: 'package_restricted',
    package_ids: ['pkg_pro', 'pkg_school'],
    is_published: true,
    is_enabled: true,
    time_limit_minutes: 60,
    total_marks: 50,
    question_count: 25,
    pdf_url: '/downloads/class5_olympiad_mock1.pdf',
    has_answer_key: true,
    has_step_by_step_solutions: true,
    has_hints: true,
    sort_order: 5,
  },
];

export const INITIAL_PACKAGES: PackageItem[] = [
  {
    id: 'pkg_free',
    code: 'FREE_TRIAL',
    name: 'Free Trial / Starter',
    priceINR: 0,
    priceUSD: 0,
    validityDays: 14,
    eligibleClassIds: ['class_1', 'class_2', 'class_3', 'class_4', 'class_5', 'class_6', 'class_7', 'class_8'],
    description: 'Introductory preview with sample practice papers across all 8 grades.',
    isEnabled: true,
    practicePaperLimit: 5,
    customPaperLimit: 1,
    targetAudience: 'New Students & Parents',
    features: {
      allCurriculumAccess: false,
      practicePapers: true,
      detailedStepSolutions: true,
      pdfDownload: true,
      mcqs: true,
      flashCards: true,
      customPapers: false,
      aiFeatures: false,
      analyticsDashboard: false,
      teacherBranding: false,
      batchManagement: false,
      prioritySupport: false,
    },
  },
  {
    id: 'pkg_basic',
    code: 'CORE_FOUNDATION',
    name: 'Core Foundations Pass',
    priceINR: 749,
    priceUSD: 12,
    validityDays: 180,
    eligibleClassIds: ['class_1', 'class_2', 'class_3', 'class_4', 'class_5', 'class_6', 'class_7', 'class_8'],
    description: '6-Month unlimited access to syllabus practice papers and solutions.',
    isEnabled: true,
    practicePaperLimit: 80,
    customPaperLimit: 15,
    targetAudience: 'Class 1 to 8 Students',
    features: {
      allCurriculumAccess: true,
      practicePapers: true,
      detailedStepSolutions: true,
      pdfDownload: true,
      mcqs: true,
      flashCards: true,
      customPapers: true,
      aiFeatures: false,
      analyticsDashboard: true,
      teacherBranding: false,
      batchManagement: false,
      prioritySupport: false,
    },
  },
  {
    id: 'pkg_pro',
    code: 'OLYMPIAD_PRO',
    name: 'Olympiad & Complete Math Mastery',
    priceINR: 1499,
    priceUSD: 24,
    validityDays: 365,
    eligibleClassIds: ['class_1', 'class_2', 'class_3', 'class_4', 'class_5', 'class_6', 'class_7', 'class_8'],
    description: '1-Year full platform access including Olympiad papers, unlimited custom test generator, and AI explainer.',
    isEnabled: true,
    practicePaperLimit: -1,
    customPaperLimit: -1,
    targetAudience: 'Ambitious Students & Top Rankers',
    features: {
      allCurriculumAccess: true,
      practicePapers: true,
      detailedStepSolutions: true,
      pdfDownload: true,
      mcqs: true,
      flashCards: true,
      customPapers: true,
      aiFeatures: true,
      analyticsDashboard: true,
      teacherBranding: false,
      batchManagement: false,
      prioritySupport: true,
    },
  },
  {
    id: 'pkg_school',
    code: 'INSTITUTE_ENTERPRISE',
    name: 'School & Teacher Multi-Student Suite',
    priceINR: 4999,
    priceUSD: 79,
    validityDays: 365,
    eligibleClassIds: ['class_1', 'class_2', 'class_3', 'class_4', 'class_5', 'class_6', 'class_7', 'class_8'],
    description: 'Batch roster management, custom printable watermark with school logo, and bulk question exports.',
    isEnabled: true,
    practicePaperLimit: -1,
    customPaperLimit: -1,
    targetAudience: 'Schools, Tutors & Coaching Centers',
    features: {
      allCurriculumAccess: true,
      practicePapers: true,
      detailedStepSolutions: true,
      pdfDownload: true,
      mcqs: true,
      flashCards: true,
      customPapers: true,
      aiFeatures: true,
      analyticsDashboard: true,
      teacherBranding: true,
      batchManagement: true,
      prioritySupport: true,
    },
  },
];

export const INITIAL_STUDENTS: Student[] = [
  {
    id: 'stu_1',
    name: 'Aarav Sharma',
    email: 'aarav.sharma@gmail.com',
    mobile: '+91 98765 43210',
    classId: 'class_5',
    board: 'CBSE',
    packageId: 'pkg_pro',
    packageName: 'Olympiad & Complete Math Mastery',
    packageStatus: 'active',
    purchaseDate: '2026-06-15',
    expiryDate: '2027-06-15',
    paymentStatus: 'successful',
    accountStatus: 'active',
    lastLogin: '2026-08-16 19:40',
    customPaperCountUsed: 8,
    customPaperLimit: -1,
    createdAt: '2026-06-15',
  },
  {
    id: 'stu_2',
    name: 'Ananya Verma',
    email: 'ananya.v@outlook.com',
    mobile: '+91 98123 45678',
    classId: 'class_6',
    board: 'ICSE',
    packageId: 'pkg_basic',
    packageName: 'Core Foundations Pass',
    packageStatus: 'active',
    purchaseDate: '2026-07-01',
    expiryDate: '2026-12-31',
    paymentStatus: 'successful',
    accountStatus: 'active',
    lastLogin: '2026-08-15 16:20',
    customPaperCountUsed: 4,
    customPaperLimit: 15,
    createdAt: '2026-07-01',
  },
  {
    id: 'stu_3',
    name: 'Rohan Deshmukh',
    email: 'rohan.d@yahoo.in',
    mobile: '+91 97654 32109',
    classId: 'class_7',
    board: 'State Board',
    packageId: 'pkg_pro',
    packageName: 'Olympiad & Complete Math Mastery',
    packageStatus: 'expired',
    purchaseDate: '2025-08-01',
    expiryDate: '2026-08-01',
    paymentStatus: 'successful',
    accountStatus: 'active',
    lastLogin: '2026-08-10 11:30',
    customPaperCountUsed: 35,
    customPaperLimit: -1,
    createdAt: '2025-08-01',
  },
  {
    id: 'stu_4',
    name: 'Diya Patel',
    email: 'diya.patel@gmail.com',
    mobile: '+91 99887 76655',
    classId: 'class_4',
    board: 'CBSE',
    packageId: 'pkg_free',
    packageName: 'Free Trial / Starter',
    packageStatus: 'active',
    purchaseDate: '2026-08-10',
    expiryDate: '2026-08-24',
    paymentStatus: 'successful',
    accountStatus: 'active',
    lastLogin: '2026-08-16 14:10',
    customPaperCountUsed: 1,
    customPaperLimit: 1,
    createdAt: '2026-08-10',
  },
];

export const INITIAL_PAYMENTS: PaymentTransaction[] = [
  {
    id: 'txn_101',
    studentId: 'stu_1',
    studentName: 'Aarav Sharma',
    studentEmail: 'aarav.sharma@gmail.com',
    studentMobile: '+91 98765 43210',
    orderId: 'ORD_2026_98214',
    packageId: 'pkg_pro',
    packageName: 'Olympiad & Complete Math Mastery',
    classId: 'class_5',
    amount: 1499,
    currency: 'INR',
    paymentGateway: 'Razorpay',
    paymentMethod: 'UPI (Google Pay)',
    status: 'successful',
    paymentDate: '2026-06-15 14:32',
    transactionId: 'pay_RZP_991823719',
    packageActivationDate: '2026-06-15',
    packageExpiryDate: '2027-06-15',
    invoiceNumber: 'INV-2026-00412',
  },
  {
    id: 'txn_102',
    studentId: 'stu_2',
    studentName: 'Ananya Verma',
    studentEmail: 'ananya.v@outlook.com',
    studentMobile: '+91 98123 45678',
    orderId: 'ORD_2026_99341',
    packageId: 'pkg_basic',
    packageName: 'Core Foundations Pass',
    classId: 'class_6',
    amount: 749,
    currency: 'INR',
    paymentGateway: 'Razorpay',
    paymentMethod: 'Netbanking (HDFC)',
    status: 'successful',
    paymentDate: '2026-07-01 10:15',
    transactionId: 'pay_RZP_118239012',
    packageActivationDate: '2026-07-01',
    packageExpiryDate: '2026-12-31',
    invoiceNumber: 'INV-2026-00523',
  },
  {
    id: 'txn_103',
    studentId: 'stu_3',
    studentName: 'Rohan Deshmukh',
    studentEmail: 'rohan.d@yahoo.in',
    studentMobile: '+91 97654 32109',
    orderId: 'ORD_2026_99499',
    packageId: 'pkg_pro',
    packageName: 'Olympiad & Complete Math Mastery',
    classId: 'class_7',
    amount: 1499,
    currency: 'INR',
    paymentGateway: 'UPI',
    paymentMethod: 'Direct QR Code',
    status: 'pending',
    paymentDate: '2026-08-16 18:20',
    transactionId: 'UPI_REF_9912830182',
    packageActivationDate: '2026-08-16',
    packageExpiryDate: '2027-08-16',
    invoiceNumber: 'INV-2026-00781',
  },
];

export const INITIAL_DASHBOARD_CONFIG: DashboardFeatureConfig = {
  practicePapers: true,
  questionBank: true,
  mcqs: true,
  flashCards: true,
  notes: true,
  previousPapers: true,
  solutions: true,
  progress: true,
  reports: true,
  downloads: true,
  customPracticePaper: true,
  notifications: true,
  announcements: true,
  aiTutor: true,
};

export const INITIAL_GLOBAL_SETTINGS: GlobalWebsiteSettings = {
  siteName: 'Beyond Classroom',
  siteTagline: 'Empowering Class 1 to 8 Mathematics Excellence',
  metaDescription: 'India’s most trusted K-8 mathematics platform with curated worksheets, step-by-step solutions, and Olympiad mastery sets.',
  supportEmail: 'support@beyondclassroom.in',
  supportPhone: '+91 80 4718 9000',
  supportAddress: 'Beyond Classroom EdTech Campus, Indiranagar, Bengaluru, Karnataka 560038',
  maintenanceMode: {
    isEnabled: false,
    title: 'Scheduled Platform Optimization',
    message: 'We are upgrading our question bank and solution engines. Platform will be back online shortly.',
    expectedAvailability: 'Today at 11:00 PM IST',
  },
};

export const INITIAL_ANNOUNCEMENTS: AnnouncementItem[] = [
  {
    id: 'ann_1',
    title: 'National Mathematics Olympiad (IMO 2026) Mock Series Released',
    content: 'Specialized high-order Olympiad practice sets are now live for Class 3 through Class 8 students.',
    targetAudience: 'all',
    priority: 'high',
    isPublished: true,
    publishDate: '2026-08-15',
    author: 'Beyond Classroom Academic Council',
  },
  {
    id: 'ann_2',
    title: 'Class 5 Fractions & Decimals Concept Mastery Sprint',
    content: 'New animated hints and step-by-step proofs added to Chapter 4 (Parts & Wholes).',
    targetAudience: 'class',
    targetClassId: 'class_5',
    priority: 'normal',
    isPublished: true,
    publishDate: '2026-08-12',
    author: 'Dr. Sarah Jenkins',
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif_1',
    studentId: 'stu_1',
    title: 'New Practice Paper Unlocked',
    message: 'Chapter 5: Tenths and Hundredths Practice Set 2 is now ready for your Class 5 track.',
    type: 'info',
    isRead: false,
    date: '2026-08-16 15:00',
  },
  {
    id: 'notif_2',
    studentId: 'stu_3',
    title: 'Subscription Expiry Notice',
    message: 'Your Olympiad & Complete Math Mastery Pass expired on Aug 1. Renew to restore download access.',
    type: 'warning',
    isRead: false,
    date: '2026-08-10 09:00',
  },
];

export const INITIAL_AUDIT_LOGS: AdminActivityLog[] = [
  {
    id: 'log_1',
    adminId: 'adm_1',
    adminName: 'Super Administrator',
    adminRole: 'super_admin',
    action: 'Student Override Configured',
    entity: 'Student Management',
    details: 'Enabled custom paper generator override for Aarav Sharma (stu_1)',
    ipAddress: '103.21.124.5',
    timestamp: '2026-08-16 21:12:40',
  },
  {
    id: 'log_2',
    adminId: 'adm_2',
    adminName: 'Dr. Sarah Jenkins',
    adminRole: 'content_admin',
    action: 'Practice Paper Published',
    entity: 'Content Repository',
    details: 'Published Practice Paper 1 for Class 5 Chapter 1',
    ipAddress: '122.162.88.19',
    timestamp: '2026-08-16 18:45:10',
  },
];

export const INITIAL_EDUCATIONAL_CONTENT: EducationalContent[] = INITIAL_CONTENTS;
export const INITIAL_ACTIVITY_LOGS: AdminActivityLog[] = INITIAL_AUDIT_LOGS;

export const INITIAL_WORKSHEET_REQUESTS: WorksheetRequest[] = [
  {
    id: 'req_101',
    studentId: 'stu_1',
    studentName: 'Aarav Sharma',
    studentEmail: 'aarav.sharma@gmail.com',
    classId: 'class_5',
    className: 'Class 5 Mathematics',
    subjectId: 'subj_5_math',
    subjectName: 'Core Mathematics',
    chapterId: 'ch_5_4',
    chapterTitle: 'Parts and Wholes (Fractions)',
    topic: 'Word Problems on Equivalent Fractions and Mixed Numbers',
    difficulty: 'hard',
    numberOfQuestions: 15,
    marks: 30,
    questionType: 'competency_based',
    additionalRequirements: 'Focus on multi-step real-world word problems similar to Olympiad Level 2.',
    status: 'ready',
    adminFeedback: 'Custom worksheet generated with detailed step-by-step solutions attached.',
    readyContentId: 'cnt_5_4_pp1',
    readyPdfUrl: '/downloads/class5_fractions_master.pdf',
    requestedDate: '2026-08-12',
    updatedDate: '2026-08-14',
    completedDate: '2026-08-14',
  },
  {
    id: 'req_102',
    studentId: 'stu_1',
    studentName: 'Aarav Sharma',
    studentEmail: 'aarav.sharma@gmail.com',
    classId: 'class_5',
    className: 'Class 5 Mathematics',
    subjectId: 'subj_5_math',
    subjectName: 'Core Mathematics',
    chapterId: 'ch_5_5',
    chapterTitle: 'Tenths and Hundredths (Decimals)',
    topic: 'Decimal Place Values and Conversion Sprint',
    difficulty: 'medium',
    numberOfQuestions: 20,
    marks: 20,
    questionType: 'objective',
    additionalRequirements: 'Need 20 quick timed MCQs for upcoming school term test.',
    status: 'in_progress',
    adminFeedback: 'Curriculum team is currently preparing the answer keys and diagrams.',
    requestedDate: '2026-08-15',
    updatedDate: '2026-08-16',
  },
  {
    id: 'req_103',
    studentId: 'stu_2',
    studentName: 'Ananya Verma',
    studentEmail: 'ananya.v@outlook.com',
    classId: 'class_6',
    className: 'Class 6 Mathematics',
    subjectId: 'subj_6_math',
    subjectName: 'Core Mathematics',
    chapterId: 'ch_6_4',
    chapterTitle: 'Integers on the Number Line',
    topic: 'Addition and Subtraction of Negative Integers',
    difficulty: 'medium',
    numberOfQuestions: 10,
    marks: 20,
    questionType: 'subjective',
    status: 'submitted',
    requestedDate: '2026-08-16',
    updatedDate: '2026-08-16',
  },
];

export const INITIAL_PRACTICE_ATTEMPTS: PracticeQuizAttempt[] = [
  {
    id: 'att_101',
    studentId: 'stu_1',
    contentId: 'cnt_5_1_mcq',
    contentTitle: 'Speed Math Quiz: Place Value Sprint (20 Questions)',
    classId: 'class_5',
    subjectId: 'subj_5_math',
    chapterId: 'ch_5_1',
    totalQuestions: 20,
    correctAnswers: 18,
    score: 18,
    maxScore: 20,
    timeSpentSeconds: 740,
    completedAt: '2026-08-15 17:30',
    accuracyPercentage: 90,
    selectedAnswers: { 0: 1, 1: 2, 2: 0, 3: 3 },
  },
  {
    id: 'att_102',
    studentId: 'stu_1',
    contentId: 'cnt_5_1_pp1',
    contentTitle: 'Practice Paper 1: Place Value & Operations Mastery',
    classId: 'class_5',
    subjectId: 'subj_5_math',
    chapterId: 'ch_5_1',
    totalQuestions: 15,
    correctAnswers: 14,
    score: 46,
    maxScore: 50,
    timeSpentSeconds: 1820,
    completedAt: '2026-08-14 11:20',
    accuracyPercentage: 92,
    selectedAnswers: {},
  },
];


