import {
  AffiliateProfile,
  AffiliateReferral,
  AffiliateSale,
  AffiliatePayout,
  AffiliateNotification,
  AffiliateSettings,
  PackageAffiliateSetting,
} from '../types/affiliate';

export const INITIAL_AFFILIATE_SETTINGS: AffiliateSettings = {
  id: 'aff_settings_global',
  globalDiscountPercentage: 10,
  globalCommissionPercentage: 10,
  commissionCalculationBasis: 'original_price',
  minimumPayout: 500,
  programEnabled: true,
  allowSelfReferral: false,
  updatedAt: '2026-08-15 10:00:00',
};

export const INITIAL_PACKAGE_AFFILIATE_SETTINGS: PackageAffiliateSetting[] = [
  {
    id: 'pkg_aff_basic',
    packageId: 'pkg_basic',
    packageName: 'Basic Starter',
    enabled: true,
    discountPercentage: 10,
    commissionPercentage: 10,
    updatedAt: '2026-08-15 10:00:00',
  },
  {
    id: 'pkg_aff_pro',
    packageId: 'pkg_pro',
    packageName: 'Pro Math Master',
    enabled: true,
    discountPercentage: 10,
    commissionPercentage: 10,
    updatedAt: '2026-08-15 10:00:00',
  },
  {
    id: 'pkg_aff_teachers',
    packageId: 'pkg_teachers',
    packageName: 'Teachers & Educators Toolkit',
    enabled: true,
    discountPercentage: 10,
    commissionPercentage: 10,
    updatedAt: '2026-08-15 10:00:00',
  },
  {
    id: 'pkg_aff_school',
    packageId: 'pkg_school_institute',
    packageName: 'School & Institute Institutional Pass',
    enabled: true,
    discountPercentage: 10,
    commissionPercentage: 10,
    updatedAt: '2026-08-15 10:00:00',
  },
];

export const INITIAL_AFFILIATES: AffiliateProfile[] = [
  {
    id: 'aff_1',
    userId: 'user_aff_hardik',
    fullName: 'Hardik Kabra',
    email: 'hdkabra96@gmail.com',
    mobile: '+91 98201 45678',
    city: 'Mumbai',
    country: 'India',
    status: 'approved',
    referralCode: 'BC-HARDIK10',
    referralLink: 'https://beyondclassroom.in/?ref=BC-HARDIK10',
    paymentMethod: 'upi',
    paymentDetails: {
      upiId: 'hardik@okaxis',
      accountHolderName: 'Hardik Kabra',
    },
    applicationReason:
      'Mathematics educator and founder of a local parent tutoring network in Mumbai covering Grades 1 to 8.',
    websiteOrSocial: 'https://youtube.com/@mathswithhardik',
    approvedBy: 'Admin (System)',
    approvedAt: '2026-07-01 11:30:00',
    createdAt: '2026-06-28 09:15:00',
    updatedAt: '2026-08-15 14:20:00',
    totalClicks: 248,
  },
  {
    id: 'aff_2',
    userId: 'user_aff_priya',
    fullName: 'Priya Sharma',
    email: 'priya.educator@gmail.com',
    mobile: '+91 94120 78910',
    city: 'Bangalore',
    country: 'India',
    status: 'pending',
    referralCode: '',
    referralLink: '',
    paymentMethod: 'upi',
    paymentDetails: {
      upiId: 'priyasharma@okhdfcbank',
      accountHolderName: 'Priya Sharma',
    },
    applicationReason:
      'Senior Primary School Math Coordinator & Edu-blogger sharing Olympiad worksheets with 5,000+ active WhatsApp parent members.',
    websiteOrSocial: 'https://instagram.com/maths_with_priya',
    createdAt: '2026-08-16 16:45:00',
    updatedAt: '2026-08-16 16:45:00',
    totalClicks: 0,
  },
  {
    id: 'aff_3',
    userId: 'user_aff_vikram',
    fullName: 'Vikram Sengupta',
    email: 'vikram.sengupta@kolkatatutors.org',
    mobile: '+91 98310 11223',
    city: 'Kolkata',
    country: 'India',
    status: 'approved',
    referralCode: 'BCX7K29',
    referralLink: 'https://beyondclassroom.in/?ref=BCX7K29',
    paymentMethod: 'bank_transfer',
    paymentDetails: {
      accountHolderName: 'Vikram Sengupta',
      accountNumber: '•••• •••• •••• 4421',
      ifscCode: 'HDFC0001245',
      bankName: 'HDFC Bank, Salt Lake Branch',
    },
    applicationReason:
      'Coaching institute owner preparing Class 5-8 students for CBSE and State Board examinations.',
    websiteOrSocial: 'https://kolkatatutors.org',
    approvedBy: 'Dr. Hardik Kabra',
    approvedAt: '2026-07-15 14:00:00',
    createdAt: '2026-07-10 10:20:00',
    updatedAt: '2026-08-12 11:00:00',
    totalClicks: 182,
  },
  {
    id: 'aff_4',
    userId: 'user_aff_ananya',
    fullName: 'Ananya Deshmukh',
    email: 'ananya.freecoupon@dealshub.biz',
    mobile: '+91 91234 56789',
    city: 'Pune',
    country: 'India',
    status: 'rejected',
    referralCode: '',
    referralLink: '',
    paymentMethod: 'upi',
    paymentDetails: {
      upiId: 'dealshub@upi',
      accountHolderName: 'Ananya Deshmukh',
    },
    applicationReason:
      'Coupon scrapers and cashback aggregator site looking to list Beyond Classroom coupons.',
    websiteOrSocial: 'https://dealshub.biz',
    rejectionReason:
      'Third-party automated discount scraper sites without genuine educational audience are not eligible per Affiliate Terms.',
    createdAt: '2026-08-10 08:30:00',
    updatedAt: '2026-08-11 12:00:00',
    totalClicks: 0,
  },
  {
    id: 'aff_5',
    userId: 'user_aff_rohit',
    fullName: 'Rohit Verma',
    email: 'rohit.spammer@tempmail.com',
    mobile: '+91 99999 12345',
    city: 'Delhi',
    country: 'India',
    status: 'suspended',
    referralCode: 'BC-ROHIT99',
    referralLink: 'https://beyondclassroom.in/?ref=BC-ROHIT99',
    paymentMethod: 'upi',
    paymentDetails: {
      upiId: 'rohit@paytm',
      accountHolderName: 'Rohit Verma',
    },
    applicationReason: 'Social media marketer.',
    suspensionReason:
      'Self-referral abuse and spamming unauthorized promotional emails in violation of community ethics.',
    approvedBy: 'Admin (System)',
    approvedAt: '2026-06-01 10:00:00',
    createdAt: '2026-05-25 15:10:00',
    updatedAt: '2026-08-05 18:30:00',
    totalClicks: 94,
  },
];

export const INITIAL_AFFILIATE_REFERRALS: AffiliateReferral[] = [
  {
    id: 'ref_1',
    affiliateId: 'aff_1',
    visitorId: 'vis_882190',
    studentId: 'stu_1',
    studentName: 'Aarav S.',
    studentEmail: 'aar***@example.com',
    studentClass: 'Class 5',
    referralCode: 'BC-HARDIK10',
    firstClickedAt: '2026-07-28 14:10:00',
    registeredAt: '2026-07-28 14:15:00',
    convertedAt: '2026-07-28 14:22:00',
    status: 'converted',
    createdAt: '2026-07-28 14:10:00',
  },
  {
    id: 'ref_2',
    affiliateId: 'aff_1',
    visitorId: 'vis_882191',
    studentId: 'stu_2',
    studentName: 'Diya P.',
    studentEmail: 'diy***@example.com',
    studentClass: 'Class 5',
    referralCode: 'BC-HARDIK10',
    firstClickedAt: '2026-08-01 10:05:00',
    registeredAt: '2026-08-01 10:12:00',
    convertedAt: '2026-08-01 10:20:00',
    status: 'converted',
    createdAt: '2026-08-01 10:05:00',
  },
  {
    id: 'ref_3',
    affiliateId: 'aff_1',
    visitorId: 'vis_882192',
    studentId: 'stu_3',
    studentName: 'Rohan I.',
    studentEmail: 'roh***@example.com',
    studentClass: 'Class 6',
    referralCode: 'BC-HARDIK10',
    firstClickedAt: '2026-08-05 16:30:00',
    registeredAt: '2026-08-05 16:35:00',
    convertedAt: '2026-08-05 16:42:00',
    status: 'converted',
    createdAt: '2026-08-05 16:30:00',
  },
  {
    id: 'ref_4',
    affiliateId: 'aff_1',
    visitorId: 'vis_882193',
    studentId: 'stu_4',
    studentName: 'Ananya M.',
    studentEmail: 'ana***@example.com',
    studentClass: 'Class 4',
    referralCode: 'BC-HARDIK10',
    firstClickedAt: '2026-08-10 11:20:00',
    registeredAt: '2026-08-10 11:25:00',
    convertedAt: '2026-08-10 11:32:00',
    status: 'converted',
    createdAt: '2026-08-10 11:20:00',
  },
  {
    id: 'ref_5',
    affiliateId: 'aff_1',
    visitorId: 'vis_882194',
    studentName: 'Kabir N.',
    studentEmail: 'kab***@example.com',
    studentClass: 'Class 7',
    referralCode: 'BC-HARDIK10',
    firstClickedAt: '2026-08-14 09:15:00',
    registeredAt: '2026-08-14 09:20:00',
    status: 'registered',
    createdAt: '2026-08-14 09:15:00',
  },
  {
    id: 'ref_6',
    affiliateId: 'aff_1',
    visitorId: 'vis_882195',
    studentName: 'Meera K.',
    studentEmail: 'mee***@example.com',
    studentClass: 'Class 3',
    referralCode: 'BC-HARDIK10',
    firstClickedAt: '2026-08-17 17:00:00',
    registeredAt: '2026-08-17 17:05:00',
    status: 'registered',
    createdAt: '2026-08-17 17:00:00',
  },
  {
    id: 'ref_7',
    affiliateId: 'aff_1',
    visitorId: 'vis_882196',
    referralCode: 'BC-HARDIK10',
    firstClickedAt: '2026-08-18 07:45:00',
    status: 'clicked',
    createdAt: '2026-08-18 07:45:00',
  },
];

export const INITIAL_AFFILIATE_SALES: AffiliateSale[] = [
  {
    id: 'sale_101',
    affiliateId: 'aff_1',
    studentId: 'stu_1',
    studentName: 'Aarav S.',
    studentEmail: 'aar***@example.com',
    purchaseId: 'pay_77218901',
    packageId: 'pkg_pro',
    packageName: 'Pro Math Master (Class 5-8)',
    classId: 'class_5',
    className: 'Class 5',
    originalAmount: 1999,
    discountPercentage: 10,
    discountAmount: 199.9,
    finalAmount: 1799.1,
    commissionPercentage: 10,
    commissionBase: 'original_price',
    commissionAmount: 199.9,
    paymentStatus: 'successful',
    status: 'paid',
    createdAt: '2026-07-28 14:22:00',
    paidAt: '2026-08-05 10:00:00',
  },
  {
    id: 'sale_102',
    affiliateId: 'aff_1',
    studentId: 'stu_2',
    studentName: 'Diya P.',
    studentEmail: 'diy***@example.com',
    purchaseId: 'pay_77218902',
    packageId: 'pkg_teachers',
    packageName: 'Teachers & Educators Toolkit',
    classId: 'class_5',
    className: 'Class 5',
    originalAmount: 3499,
    discountPercentage: 10,
    discountAmount: 349.9,
    finalAmount: 3149.1,
    commissionPercentage: 10,
    commissionBase: 'original_price',
    commissionAmount: 349.9,
    paymentStatus: 'successful',
    status: 'paid',
    createdAt: '2026-08-01 10:20:00',
    paidAt: '2026-08-05 10:00:00',
  },
  {
    id: 'sale_103',
    affiliateId: 'aff_1',
    studentId: 'stu_3',
    studentName: 'Rohan I.',
    studentEmail: 'roh***@example.com',
    purchaseId: 'pay_77218903',
    packageId: 'pkg_pro',
    packageName: 'Pro Math Master (Class 5-8)',
    classId: 'class_6',
    className: 'Class 6',
    originalAmount: 1999,
    discountPercentage: 10,
    discountAmount: 199.9,
    finalAmount: 1799.1,
    commissionPercentage: 10,
    commissionBase: 'original_price',
    commissionAmount: 199.9,
    paymentStatus: 'successful',
    status: 'approved',
    createdAt: '2026-08-05 16:42:00',
  },
  {
    id: 'sale_104',
    affiliateId: 'aff_1',
    studentId: 'stu_4',
    studentName: 'Ananya M.',
    studentEmail: 'ana***@example.com',
    purchaseId: 'pay_77218904',
    packageId: 'pkg_basic',
    packageName: 'Basic Starter (Class 1-4)',
    classId: 'class_4',
    className: 'Class 4',
    originalAmount: 999,
    discountPercentage: 10,
    discountAmount: 99.9,
    finalAmount: 899.1,
    commissionPercentage: 10,
    commissionBase: 'original_price',
    commissionAmount: 99.9,
    paymentStatus: 'successful',
    status: 'pending',
    createdAt: '2026-08-10 11:32:00',
  },
  {
    id: 'sale_105',
    affiliateId: 'aff_3',
    studentId: 'stu_5',
    studentName: 'Kavya S.',
    studentEmail: 'kav***@example.com',
    purchaseId: 'pay_77218905',
    packageId: 'pkg_school_institute',
    packageName: 'School & Institute Institutional Pass',
    classId: 'class_8',
    className: 'Class 8',
    originalAmount: 7999,
    discountPercentage: 10,
    discountAmount: 799.9,
    finalAmount: 7199.1,
    commissionPercentage: 10,
    commissionBase: 'original_price',
    commissionAmount: 799.9,
    paymentStatus: 'successful',
    status: 'approved',
    createdAt: '2026-08-12 15:10:00',
  },
];

export const INITIAL_AFFILIATE_PAYOUTS: AffiliatePayout[] = [
  {
    id: 'payout_801',
    affiliateId: 'aff_1',
    affiliateName: 'Hardik Kabra',
    affiliateEmail: 'hdkabra96@gmail.com',
    amount: 549.8,
    paymentMethod: 'upi',
    paymentDetails: {
      upiId: 'hardik@okaxis',
      accountHolderName: 'Hardik Kabra',
    },
    status: 'paid',
    requestedAt: '2026-08-02 09:00:00',
    approvedAt: '2026-08-04 14:30:00',
    paidAt: '2026-08-05 10:00:00',
    transactionReference: 'UPI/AXIS/20260805100021/REF54980',
    adminNotes: 'Processed via Axis UPI Auto-Payout gateway.',
    createdAt: '2026-08-02 09:00:00',
  },
];

export const INITIAL_AFFILIATE_NOTIFICATIONS: AffiliateNotification[] = [
  {
    id: 'notif_aff_1',
    affiliateId: 'aff_1',
    title: '🎉 Affiliate Application Approved!',
    message:
      'Congratulations! Your affiliate application has been approved. Your unique referral code is BC-HARDIK10.',
    type: 'approval',
    isRead: true,
    createdAt: '2026-07-01 11:30:00',
  },
  {
    id: 'notif_aff_2',
    affiliateId: 'aff_1',
    title: '💰 New Referral Sale: Pro Math Master',
    message:
      'A student registered with your referral link just purchased the Pro Math Master package. You earned ₹199.90 commission!',
    type: 'sale',
    isRead: true,
    createdAt: '2026-07-28 14:22:00',
  },
  {
    id: 'notif_aff_3',
    affiliateId: 'aff_1',
    title: '✅ Monthly Payout Processed',
    message:
      'Payout request #payout_801 of ₹549.80 has been successfully transferred to UPI: hardik@okaxis.',
    type: 'payout',
    isRead: true,
    createdAt: '2026-08-05 10:00:00',
  },
  {
    id: 'notif_aff_4',
    affiliateId: 'aff_1',
    title: '🎯 New Student Registration',
    message:
      'A new student (Meera K., Class 3) just registered using your referral code BC-HARDIK10.',
    type: 'registration',
    isRead: false,
    createdAt: '2026-08-17 17:05:00',
  },
];
